# Generated by Django 6.0.5 on 2026-05-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=254)),
                ('tel_number', models.CharField(max_length=12)),
                ('topic', models.TextField()),
            ],
            options={
                'db_table': 'work',
                'ordering': ['-id'],
            },
        ),
    ]
