# Generated by Django 5.2.14 on 2026-05-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('email', models.CharField()),
                ('tel_number', models.CharField(max_length=12)),
                ('topic', models.TextField()),
            ],
            options={
                'db_table': 'work',
                'ordering': ['-id'],
            },
        ),
    ]
